# Generated by Django 4.2.2 on 2023-09-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="libraryexercise", name="id",),
        migrations.RemoveField(model_name="libraryexercise", name="library",),
        migrations.AddField(
            model_name="libraryexercise",
            name="profile",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="library",
                serialize=False,
                to="api_users.profile",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Library",),
    ]
