# Generated by Django 4.2.2 on 2023-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0002_remove_libraryexercise_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryexercise",
            name="max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
