# Generated by Django 4.2.2 on 2023-09-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0004_alter_libraryexercise_bodypart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryexercise",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_exercises",
                to="api_users.profile",
            ),
        ),
    ]
