# Generated by Django 4.2.2 on 2023-09-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0005_libraryexercise_id_alter_libraryexercise_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(name="exercise", options={},),
        migrations.AlterModelOptions(
            name="libraryexercise", options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to="api_users.profile",
            ),
        ),
    ]
