# Generated by Django 4.2.2 on 2023-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0009_alter_exset_percent_alter_exset_reps_alter_exset_set_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="programweekexercise",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="programweekexercise",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exset",
            name="set",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
