# Generated by Django 4.2.2 on 2023-09-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0010_programweekexercise_name_programweekexercise_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPrimaryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "prg_wk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exs",
                        to="api_users.programweek",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="programweekexercise", old_name="order", new_name="day",
        ),
        migrations.RenameField(
            model_name="programweekexercise",
            old_name="program_week",
            new_name="prg_wk",
        ),
        migrations.AddField(
            model_name="programweekexercise",
            name="is_primary",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ProgramSecondaryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "primary_ex",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondaries",
                        to="api_users.programprimaryexercise",
                    ),
                ),
            ],
        ),
    ]
