# Generated by Django 4.2.2 on 2023-09-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0012_rename_prog_exercise_exset_prg_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exset",
            name="prg_primary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="api_users.programprimaryexercise",
            ),
        ),
    ]
