# Generated by Django 4.2.2 on 2023-09-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0013_alter_exset_prg_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="exset",
            name="prg_secondary",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="api_users.programsecondaryexercise",
            ),
        ),
    ]
