# Generated by Django 4.2.2 on 2023-09-25 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0014_exset_prg_secondary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exset", old_name="prg_primary", new_name="primary_ex",
        ),
        migrations.RenameField(
            model_name="exset", old_name="prg_secondary", new_name="secondary_ex",
        ),
        migrations.RenameField(model_name="exset", old_name="set", new_name="sets",),
        migrations.AlterField(
            model_name="exset",
            name="percent",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
