# Generated by Django 4.2.2 on 2023-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0015_rename_prg_primary_exset_primary_ex_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exset", old_name="wrkt_exercise", new_name="wrkt_ex",
        ),
    ]
