# Generated by Django 4.2.2 on 2023-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0016_rename_wrkt_exercise_exset_wrkt_ex"),
    ]

    operations = [
        migrations.AddField(
            model_name="programweek", name="data", field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(name="ProgramWeekExercise",),
    ]
