# Generated by Django 4.2.2 on 2023-09-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0017_programweek_data_delete_programweekexercise"),
    ]

    operations = [
        migrations.RemoveField(model_name="exset", name="secondary_ex",),
        migrations.DeleteModel(name="ProgramSecondaryExercise",),
    ]
