# Generated by Django 4.2.2 on 2023-09-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0018_remove_exset_secondary_ex_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProgramPrimaryExercise", new_name="ProgramExercise",
        ),
        migrations.RenameField(
            model_name="exset", old_name="primary_ex", new_name="program_ex",
        ),
    ]
