# Generated by Django 4.2.2 on 2023-09-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0019_rename_programprimaryexercise_programexercise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programexercise", old_name="prg_wk", new_name="program_week",
        ),
        migrations.RemoveField(model_name="programweek", name="data",),
        migrations.CreateModel(
            name="AccessoryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "primary_ex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="api_users.programexercise",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exset",
            name="accessory_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="api_users.accessoryexercise",
            ),
        ),
    ]
