# Generated by Django 4.2.2 on 2023-09-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0020_rename_prg_wk_programexercise_program_week_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="programweek", options={"ordering": ["id"]},),
        migrations.RemoveField(model_name="programweek", name="order",),
    ]
