# Generated by Django 4.2.2 on 2023-09-25 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0022_alter_programexercise_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="duration",
            field=models.IntegerField(
                default=8,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
    ]
