# Generated by Django 4.2.2 on 2023-09-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0027_programexercise_week"),
    ]

    operations = [
        migrations.RemoveField(model_name="programexercise", name="week",),
    ]
