# Generated by Django 4.2.2 on 2023-09-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0030_alter_exset_options_alter_programexercise_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessoryexercise",
            name="program_ex",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessory",
                to="api_users.programexercise",
            ),
        ),
    ]
