# Generated by Django 4.2.2 on 2023-09-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0031_alter_accessoryexercise_program_ex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessoryexercise", options={"ordering": ["program_ex"]},
        ),
    ]
