# Generated by Django 4.2.2 on 2023-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0032_alter_accessoryexercise_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccessoryExercise", new_name="ProgramAccessory",
        ),
        migrations.AlterField(
            model_name="programexercise",
            name="day",
            field=models.IntegerField(default=0),
        ),
    ]
