# Generated by Django 4.2.2 on 2023-09-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0034_alter_exset_percent_alter_program_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="programweek", options={"ordering": ["id"]},),
        migrations.RemoveField(model_name="programweek", name="week",),
    ]
