# Generated by Django 4.2.2 on 2023-09-26 22:40

import utils.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0037_program_startdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programweek",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="programweek",
            name="order",
            field=utils.fields.RangeIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
    ]
