# Generated by Django 4.2.2 on 2023-09-27 17:12

import django.core.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0038_alter_programweek_options_programweek_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="programaccessory", options={},),
        migrations.AlterField(
            model_name="profile",
            name="day_one_wkday",
            field=utils.fields.RangeIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="dayid",
            field=utils.fields.RangeIntegerField(null=True),
        ),
    ]
