# Generated by Django 4.2.2 on 2023-09-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0040_alter_workout_options_remove_workout_dayid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayexercise", old_name="workout", new_name="day",
        ),
        migrations.RemoveField(model_name="day", name="profile",),
        migrations.AddField(
            model_name="day",
            name="workout",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="api_users.workout",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workout",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="api_users.profile",
            ),
        ),
    ]
