# Generated by Django 4.2.2 on 2023-09-27 20:36

import django.core.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0041_rename_workout_dayexercise_day_remove_day_profile_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayexercise", options={"ordering": ["day", "order"]},
        ),
        migrations.AddField(
            model_name="workout",
            name="order",
            field=utils.fields.RangeIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
