# Generated by Django 4.2.2 on 2023-10-05 22:21

import django.core.validators
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0042_alter_dayexercise_options_workout_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout", options={"ordering": ["active", "name"]},
        ),
        migrations.AddField(
            model_name="workout",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="workout",
            name="order",
            field=utils.fields.RangeIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
    ]
