# Generated by Django 4.2.2 on 2023-10-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0043_alter_workout_options_workout_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program", options={"ordering": ["-active", "order"]},
        ),
        migrations.AlterModelOptions(
            name="workout", options={"ordering": ["-active", "name"]},
        ),
        migrations.AddField(
            model_name="program",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
