# Generated by Django 4.2.2 on 2023-10-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0046_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondaryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary",
                        to="api_users.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("sets", models.CharField(blank=True, default="", max_length=50)),
                ("reps", models.CharField(blank=True, default="", max_length=50)),
                ("weight", models.CharField(blank=True, default="", max_length=50)),
                ("percent", models.FloatField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="api_users.exercise",
                    ),
                ),
                (
                    "secondary_exercise",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="api_users.secondaryexercise",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
