# Generated by Django 4.2.2 on 2023-10-11 19:39

import django.core.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0048_exerciseset_secondaryexercise_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="exset", name="accessory_ex",),
        migrations.RemoveField(model_name="exset", name="program_ex",),
        migrations.RemoveField(model_name="exset", name="wrkt_ex",),
        migrations.RemoveField(model_name="programaccessory", name="program_ex",),
        migrations.RemoveField(model_name="programexercise", name="week",),
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=utils.fields.RangeIntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(16),
                ],
            ),
        ),
        migrations.DeleteModel(name="DayExercise",),
        migrations.DeleteModel(name="ExSet",),
        migrations.DeleteModel(name="ProgramAccessory",),
        migrations.DeleteModel(name="ProgramExercise",),
    ]
