# Generated by Django 4.2.2 on 2023-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0049_remove_exset_accessory_ex_remove_exset_program_ex_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(name="workout", options={"ordering": ["order"]},),
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="program",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(default="New Workout", max_length=50),
        ),
    ]
