# Generated by Django 4.2.2 on 2023-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0050_alter_workout_options_alter_program_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(default="New Program", max_length=50),
        ),
    ]
