# Generated by Django 4.2.2 on 2023-10-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0052_alter_exercise_order_orderedexa"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedexa",
            name="programweek",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ord_exs",
                to="api_users.programweek",
            ),
        ),
        migrations.AlterField(
            model_name="orderedexa",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ord_exs",
                to="api_users.day",
            ),
        ),
    ]
