# Generated by Django 4.2.2 on 2023-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0054_bodypart_equipment"),
    ]

    operations = [
        migrations.RemoveField(model_name="day", name="groups",),
        migrations.AddField(
            model_name="day",
            name="bodyparts",
            field=models.ManyToManyField(to="api_users.bodypart"),
        ),
    ]
