# Generated by Django 4.2.2 on 2023-10-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0055_remove_day_groups_day_bodyparts"),
    ]

    operations = [
        migrations.RemoveField(model_name="day", name="bodyparts",),
    ]
