# Generated by Django 4.2.2 on 2023-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0057_delete_bodypart_delete_equipment"),
    ]

    operations = [
        migrations.AlterModelOptions(name="day", options={"ordering": ["order"]},),
        migrations.RemoveField(model_name="day", name="dayid",),
        migrations.RemoveField(model_name="workout", name="active",),
        migrations.AddField(
            model_name="day",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is_active"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
