# Generated by Django 4.2.2 on 2023-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0058_alter_day_options_remove_day_dayid_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="workout", name="is_active",),
        migrations.AddField(
            model_name="workout",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="active"
            ),
        ),
    ]
