# Generated by Django 4.2.2 on 2023-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0059_remove_workout_is_active_workout_active"),
    ]

    operations = [
        migrations.AlterModelOptions(name="day", options={},),
        migrations.RemoveField(model_name="day", name="order",),
        migrations.AddField(
            model_name="day",
            name="day_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
