# Generated by Django 4.2.2 on 2023-10-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0060_alter_day_options_remove_day_order_day_day_id"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderedExA",),
    ]
