# Generated by Django 4.2.2 on 2023-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0061_delete_orderedexa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(blank=True, default="New Workout", max_length=50),
        ),
    ]
