# Generated by Django 4.2.2 on 2023-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0063_remove_workout_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="active"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(default="New Workout", max_length=50),
        ),
    ]
