# Generated by Django 4.2.2 on 2023-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0064_workout_active_alter_workout_name"),
    ]

    operations = [
        migrations.AlterModelOptions(name="programweek", options={},),
        migrations.AlterField(
            model_name="program",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
