# Generated by Django 4.2.2 on 2023-11-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0065_alter_programweek_options_alter_program_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="programweek", name="order",),
        migrations.AddField(
            model_name="program",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="active"
            ),
        ),
        migrations.AddField(
            model_name="programweek",
            name="week_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
