# Generated by Django 4.2.2 on 2023-11-03 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0066_remove_programweek_order_program_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="day_one_wkday",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(6)]
            ),
        ),
    ]
