# Generated by Django 4.2.2 on 2023-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0069_alter_exercise_day_alter_exercise_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="exerciseset", options={},),
        migrations.AddField(
            model_name="secondaryexercise",
            name="percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondaryexercise",
            name="reps",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="secondaryexercise",
            name="sets",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="secondaryexercise",
            name="weight",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="order",
            field=models.PositiveIntegerField(db_index=True, verbose_name="order"),
        ),
    ]
