# Generated by Django 4.2.2 on 2023-11-09 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0070_alter_exerciseset_options_secondaryexercise_percent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                blank=True, default=datetime.date.today, verbose_name="Date"
            ),
        ),
    ]
