# Generated by Django 4.2.2 on 2023-11-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0071_alter_program_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(blank=True, default="New Program", max_length=50),
        ),
    ]
