# Generated by Django 4.2.2 on 2023-11-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0073_alter_program_startdate_alter_programweek_week_id"),
    ]

    operations = [
        migrations.RenameModel(old_name="ProgramWeek", new_name="Week",),
    ]
