# Generated by Django 4.2.2 on 2023-11-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0075_alter_program_active_alter_program_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
