# Generated by Django 4.2.2 on 2023-11-13 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0076_alter_workout_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryexercise",
            name="bodypart",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHST", "Chest"),
                    ("BACK", "Back"),
                    ("ARMS", "Arms"),
                    ("SHLD", "Shoulders"),
                    ("LEGS", "Legs"),
                    ("CORE", "Core"),
                    ("", "None"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="equipment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRBL", "barbell"),
                    ("EZBR", "ez_bar"),
                    ("DUMB", "dumbell"),
                    ("CABL", "cable"),
                    ("SMTH", "sm"),
                    ("MACH", "machine"),
                    ("BODY", "bodyweight"),
                    ("FREE", "freeweight"),
                    ("BAND", "bands"),
                    ("", "None"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="week_id",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
