# Generated by Django 4.2.2 on 2023-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0077_alter_libraryexercise_bodypart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryexercise",
            name="bodypart",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chest", "Chest"),
                    ("back", "Back"),
                    ("arms", "Arms"),
                    ("shoulders", "Shoulders"),
                    ("legs", "Legs"),
                    ("core", "Core"),
                    ("", "None"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="equipment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barbell", "barbell"),
                    ("ez_bar", "ez_bar"),
                    ("dumbell", "dumbell"),
                    ("cable", "cable"),
                    ("sm", "sm"),
                    ("machine", "machine"),
                    ("bodyweight", "bodyweight"),
                    ("freeweight", "freeweight"),
                    ("bands", "bands"),
                    ("", "None"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
