# Generated by Django 4.2.2 on 2023-11-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0080_alter_workout_options_remove_workout_modified_date"),
    ]

    operations = [
        migrations.AlterModelOptions(name="workout", options={"ordering": ["order"]},),
    ]
