# Generated by Django 4.2.2 on 2023-11-29 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0081_alter_workout_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="time_offset",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="time_offset",
            ),
        ),
    ]
