# Generated by Django 4.2.2 on 2023-12-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0082_profile_time_offset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout", options={"ordering": ["-active", "order"]},
        ),
        migrations.AddField(
            model_name="workout",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
