# Generated by Django 4.2.2 on 2023-12-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0083_alter_workout_options_workout_date_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout", options={"ordering": ["-active", "date_modified"]},
        ),
        migrations.AlterField(
            model_name="workout",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="api_users.profile",
            ),
        ),
    ]
