# Generated by Django 4.2.2 on 2023-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0084_alter_workout_options_alter_workout_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(blank=True, default="New Workout", max_length=50),
        ),
    ]
