# Generated by Django 4.2.2 on 2023-12-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0085_alter_workout_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout", options={"ordering": ["-is_active", "date_modified"]},
        ),
        migrations.RenameField(
            model_name="workout", old_name="active", new_name="is_active",
        ),
    ]
