# Generated by Django 4.2.2 on 2023-12-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0086_alter_workout_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={
                "default_manager_name": "objects",
                "ordering": ["-is_active", "date_modified"],
            },
        ),
    ]
