# Generated by Django 4.2.2 on 2023-12-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0087_alter_workout_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="workout", options={"ordering": ["order"]},),
        migrations.RemoveField(model_name="workout", name="date_modified",),
    ]
