# Generated by Django 4.2.2 on 2023-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0088_alter_workout_options_remove_workout_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
            ),
        ),
    ]
