# Generated by Django 4.2.2 on 2023-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0089_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
