# Generated by Django 4.2.2 on 2023-12-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0090_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_library",
                to="api_users.profile",
            ),
        ),
        migrations.CreateModel(
            name="DefaultLibraryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library",
                        to="api_users.profile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="CustomLibraryExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "bodypart",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("arms", "Arms"),
                            ("shoulders", "Shoulders"),
                            ("legs", "Legs"),
                            ("core", "Core"),
                            ("", "None"),
                        ],
                        default="",
                        max_length=9,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("barbell", "barbell"),
                            ("ez_bar", "ez_bar"),
                            ("dumbell", "dumbell"),
                            ("cable", "cable"),
                            ("sm", "sm"),
                            ("machine", "machine"),
                            ("bodyweight", "bodyweight"),
                            ("freeweight", "freeweight"),
                            ("bands", "bands"),
                            ("", "None"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs",
                        to="api_users.profile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
