# Generated by Django 4.2.2 on 2023-12-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_users",
            "0091_alter_libraryexercise_profile_defaultlibraryexercise_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customlibraryexercise", options={"default_related_name": "customs"},
        ),
        migrations.AlterModelOptions(
            name="defaultlibraryexercise", options={"default_related_name": "library"},
        ),
        migrations.AddField(
            model_name="defaultlibraryexercise",
            name="bodypart",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chest", "Chest"),
                    ("back", "Back"),
                    ("arms", "Arms"),
                    ("shoulders", "Shoulders"),
                    ("legs", "Legs"),
                    ("core", "Core"),
                    ("", "None"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="defaultlibraryexercise",
            name="equipment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("barbell", "barbell"),
                    ("ez_bar", "ez_bar"),
                    ("dumbell", "dumbell"),
                    ("cable", "cable"),
                    ("sm", "sm"),
                    ("machine", "machine"),
                    ("bodyweight", "bodyweight"),
                    ("freeweight", "freeweight"),
                    ("bands", "bands"),
                    ("", "None"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="defaultlibraryexercise",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customlibraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_users.profile"
            ),
        ),
        migrations.AlterField(
            model_name="defaultlibraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_users.profile"
            ),
        ),
    ]
