# Generated by Django 4.2.2 on 2023-12-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0093_alter_customlibraryexercise_bodypart_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="defaultlibraryexercise", name="profile",),
        migrations.AlterField(
            model_name="libraryexercise",
            name="bodypart",
            field=models.CharField(
                choices=[
                    ("CHEST", "Chest"),
                    ("BACK", "Back"),
                    ("ARMS", "Arms"),
                    ("SHOULDERS", "Shoulders"),
                    ("LEGS", "Legs"),
                    ("CORE", "Core"),
                    ("", "none"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("BARBELL", "Barbell"),
                    ("DUMBELL", "Ez Bar"),
                    ("SMITH_MACHINE", "Dumbell"),
                    ("MACHINE", "Cable"),
                    ("CABLE", "Smith Machine"),
                    ("EX_BAR", "Machine"),
                    ("BODY_WEIGHT", "Body-Weight"),
                    ("FREE_WEIGHT", "Free-Weight"),
                    ("BANDED", "Banded"),
                    ("", "none"),
                ],
                default="",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="libraryexercise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to="api_users.profile",
            ),
        ),
        migrations.DeleteModel(name="CustomLibraryExercise",),
        migrations.DeleteModel(name="DefaultLibraryExercise",),
    ]
