# Generated by Django 4.2.2 on 2024-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0096_rename_notifs_profile_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
            ),
        ),
    ]
