# Generated by Django 4.2.2 on 2024-02-21 13:45

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0097_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                default=0,
                max_length=16,
                validators=[utils.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
            preserve_default=False,
        ),
    ]
