# Generated by Django 4.2.2 on 2024-02-21 13:46

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0098_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[utils.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
    ]
