# Generated by Django 4.2.2 on 2024-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0101_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("email", ""), _negated=True), ("email__isnull", False)
                    ),
                    models.Q(
                        models.Q(("phone_number", ""), _negated=True),
                        ("phone_number__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="email_or_phone_number",
            ),
        ),
    ]
