# Generated by Django 4.2.2 on 2024-02-24 17:56

import django.contrib.auth.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0102_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=utils.fields.OptionalUniqueCharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Optional. 150 characters or fewer. Unaccented lowercase and uppercase letters, digits, and @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
