# Generated by Django 4.2.2 on 2024-02-25 14:55

import django.contrib.auth.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0103_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=utils.fields.OptionalUniqueCharField(
                help_text="Optional. 150 characters or fewer. Unaccented lowercase and uppercase letters, digits, and @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
