# Generated by Django 4.2.2 on 2024-02-26 18:11

import api.users.models.custom_user
import django.contrib.auth.validators
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0107_customuser_inactive_start_date"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", api.users.models.custom_user.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="inactive_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="inactive start date"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                validators=[utils.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=utils.fields.OptionalUniqueCharField(
                max_length=150,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
