# Generated by Django 4.2.2 on 2024-02-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0110_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
