# Generated by Django 4.2.2 on 2024-02-28 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0113_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                blank=True, default=datetime.date(2024, 2, 28), null=True
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="name",
            field=models.CharField(
                blank=True, default="New Workout", max_length=50, verbose_name="name"
            ),
        ),
    ]
