# Generated by Django 4.2.2 on 2024-02-28 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0114_alter_program_startdate_alter_workout_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="program", name="active",),
        migrations.AddField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=4, verbose_name="duration"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(
                blank=True, default="New Program", max_length=50, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                blank=True,
                default=datetime.date(2024, 2, 28),
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
