# Generated by Django 4.2.2 on 2024-03-01 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0115_remove_program_active_program_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                blank=True,
                default=datetime.date(2024, 3, 1),
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
