# Generated by Django 4.2.2 on 2024-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0117_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="start date"
            ),
        ),
    ]
