# Generated by Django 4.2.2 on 2024-04-29 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0120_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="startdate",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
