# Generated by Django 4.2.2 on 2024-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0121_alter_program_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_theme",
            field=models.CharField(
                choices=[("LGHT", "light"), ("DARK", "dark"), ("SYST", "system")],
                default="SYST",
                max_length=4,
            ),
        ),
    ]
