# Generated by Django 4.2.2 on 2024-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0122_profile_preferred_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                max_length=6,
            ),
        ),
    ]
