# Generated by Django 4.2.2 on 2024-05-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0125_rename_preferred_theme_profile_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day", old_name="day_id", new_name="day_index",
        ),
    ]
