# Generated by Django 4.2.2 on 2024-05-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0126_rename_day_id_day_day_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciseset", options={"ordering": ["order"]},
        ),
        migrations.DeleteModel(name="SecondaryExercise",),
    ]
