# Generated by Django 4.2.2 on 2024-05-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0128_customuser_locale"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="locale",),
    ]
