# Generated by Django 4.2.2 on 2024-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0130_profile_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="libraryexercise", options={"ordering": ["id"]},
        ),
    ]
