# Generated by Django 4.2.2 on 2024-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0131_alter_libraryexercise_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="workout", options={},),
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="profile_and_name_unique"
            ),
        ),
    ]
