# Generated by Django 4.2.2 on 2024-08-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0138_rename_custom_libraryexercise_is_custom"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workout", name="profile_and_name_unique",
        ),
    ]
