# Generated by Django 4.2.2 on 2024-08-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0140_genericexercise"),
    ]

    operations = [
        migrations.DeleteModel(name="GenericExercise",),
    ]
