# Generated by Django 4.2.2 on 2024-08-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0141_delete_genericexercise"),
    ]

    operations = [
        migrations.AlterModelOptions(name="workout", options={"ordering": ["order"]},),
    ]
