# Generated by Django 4.2.2 on 2024-08-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0143_exerciseref_baseexerciseref"),
    ]

    operations = [
        migrations.DeleteModel(name="BaseExerciseRef",),
    ]
