# Generated by Django 4.2.2 on 2024-08-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_exercises",
            "0003_remove_exerciseref_ref_remove_exerciseref_user_and_more",
        ),
        ("api_users", "0145_remove_exerciseref_baseexercise_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseRef",
            fields=[
                (
                    "baseexercise_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api_exercises.baseexercise",
                    ),
                ),
                (
                    "orm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="one rep max"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("api_exercises.baseexercise",),
        ),
    ]
