# Generated by Django 4.2.2 on 2024-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_exercises",
            "0003_remove_exerciseref_ref_remove_exerciseref_user_and_more",
        ),
        ("api_users", "0147_rename_exerciseref_exercise"),
    ]

    operations = [
        migrations.RenameModel(old_name="Exercise", new_name="CustomExercise",),
    ]
