# Generated by Django 4.2.2 on 2024-08-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="name")),
                (
                    "bodypart",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("ARMS", "Arms"),
                            ("SHOULDERS", "Shoulders"),
                            ("LEGS", "Legs"),
                            ("CORE", "Core"),
                            ("", "none"),
                        ],
                        default="",
                        max_length=9,
                        verbose_name="bodypart",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("BARBELL", "Barbell"),
                            ("DUMBELL", "Dumbell"),
                            ("SMITH_MACHINE", "Smith Machine"),
                            ("MACHINE", "Machine"),
                            ("CABLE", "Cable"),
                            ("EZ_BAR", "Ez Bar"),
                            ("BODY_WEIGHT", "Body-Weight"),
                            ("FREE_WEIGHT", "Free-Weight"),
                            ("BANDED", "Banded"),
                            ("", "none"),
                        ],
                        default="",
                        max_length=13,
                        verbose_name="equipment",
                    ),
                ),
                (
                    "orm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="one rep max"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
            ],
            options={
                "permissions": [
                    (
                        "can_edit_defs",
                        "Can change the name, bodypart, and equipment for the exercise",
                    )
                ],
            },
        ),
    ]
