# Generated by Django 4.2.2 on 2024-08-22 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_exercises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="baseexercise", name="is_enabled",),
        migrations.RemoveField(model_name="baseexercise", name="orm",),
        migrations.CreateModel(
            name="ExerciseRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="one rep max"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
                (
                    "ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_exercises.baseexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "baseexercise_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api_exercises.baseexercise",
                    ),
                ),
                (
                    "orm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="one rep max"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("api_exercises.baseexercise",),
        ),
    ]
